refactor: simplify shell env caching and setup

diff --git a/private_dot_sh_env.tmpl b/private_dot_sh_env.tmpl
--- a/private_dot_sh_env.tmpl
+++ b/private_dot_sh_env.tmpl
@@ -4,7 +4,64 @@
 # {{- else -}}
 # vim:filetype=sh.chezmoitmpl
 # {{- end }}
-# Setting up various environment variables
+# {{- $shell := .shell -}}
+# {{- /* $shell := "zsh" */ -}}
+# {{- /* Only cache env on personal and non-ephemeral systems */ -}}
+# {{ "" }}
+# {{ template "sh/env_wsl.sh" . }}
+
+# {{ if .cache.build.shell -}}
+# {{- /* env_cache is sourced for non-interactive sessions */}}
+# {{- /* env_cache stores various environment variables */}}
+env_cache='# {{ .chezmoi.homeDir }}/.sh_env_cache'
+
+last_cache_file='# {{ joinPath .chezmoi.homeDir ".sh_last_cache" }}'
+
+# If not running interactively, source env cache and exit early
+if [[ $- != *i* ]] && [[ -f "$env_cache" ]]; then
+    # echo "non-interactive mode, sourcing env cache"
+    source "$env_cache"
+    return 0
+fi
+
+[[ -f "$HOME/.sh_force_cache" || -f "$HOME/sh_force_cache" ]] && sh_force_cache=true || sh_force_cache=false
+[[ -f "$HOME/sh_force_cache_once" ]] && sh_force_cache_once=true || sh_force_cache_once=false
+
+last_cache=$(cat "$last_cache_file" 2>/dev/null)
+
+if ! {
+    [[ ! -f "$env_cache" ]] ||
+        [[ "${sh_force_cache}" = "true" ]] ||
+        [[ "${sh_force_cache_once}" = "true" ]] ||
+        { [[ -n "${last_cache}" ]] && (($(date +%s) - last_cache >= 86400)); }
+}; then
+    source "$env_cache"
+    return 0
+fi
+
+if [[ "$sh_force_cache_once" = "true" ]] && [[ -f "$HOME/sh_force_cache_once" ]]; then
+    rm "$HOME/sh_force_cache_once"
+fi
+
+if [[ "$SHLVL" -ge 2 ]]; then
+    if [[ $- != *i* ]]; then
+        if [[ ! -f "$env_cache" ]]; then
+            echo "Not running in a fresh shell, but SH environment cache is missing."
+            echo "Cache will be built, but may be dirty. Rebuild it via sh_force_cache"
+        else
+            source "$env_cache"
+            return 0
+        fi
+    elif [[ ! -f "$env_cache" ]]; then
+        echo "Not running in a fresh shell, but # {{ $shell }} cache is missing."
+        echo "Cache will be built, but may be dirty. Rebuild it via sh_force_cache"
+    else
+        source "$env_cache"
+        return 0
+    fi
+fi
+echo "Building # {{ $shell }} cache"
+# {{- end }}
 
 #
 # Miscellaneous variables
@@ -440,3 +497,20 @@ export AVANTE_GEMINI_API_KEY=# {{ .secrets.api_keys.avante.personal.gemini | quo
 # {{- end }}
 
 # {{ template "sh/env_compiler.sh" . }}
+
+
+# {{ if .cache.build.shell -}}
+{
+    echo "#!/bin/# {{ $shell }}"
+    # echo 'echo "sourcing env"'
+    # {{- if eq $shell "bash" }}
+    echo "shopt -s extglob"
+    # {{- end }}
+    declare -p | grep -vE '^declare -[^x]'
+    declare -p | grep -E '^declare -..? (__git_|__zoxide_)'
+} >"$env_cache"
+
+date +%s >"$last_cache_file"
+chmod 600 "$last_cache_file"
+chmod 600 "$env_cache"
+# {{- end -}}
